// Exercise the built provider against the pinned official ACP SDK and real HTTP.
import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import {Readable,Writable} from 'node:stream';import {pathToFileURL} from 'node:url';
const [binary,sdkFile]=process.argv.slice(2);if(!binary||!sdkFile)throw Error('Usage: node acp_client.mjs /absolute/raptor-acp /absolute/sdk/dist/acp.js');
const acp=await import(pathToFileURL(sdkFile));const root=await fs.mkdtemp(path.join(os.tmpdir(),'raptor-acp-test-'));await fs.chmod(root,0o700);let creates=0,cancelled=false,hold=false;const requests=new Map(),keys=new Map();
const server=http.createServer(async(req,res)=>{const chunks=[];for await(const b of req)chunks.push(b);const body=chunks.length?JSON.parse(Buffer.concat(chunks)):null;res.setHeader('Content-Type','application/json');const out=(v,status=200)=>{res.statusCode=status;res.end(JSON.stringify(status<400?{data:v}:v));};
 if(req.url==='/api/v1/login'){assert.deepEqual(body,{username:'fixture',password:'synthetic-password'});res.setHeader('Set-Cookie','raptor_session=fixture-session; Path=/; HttpOnly');return out({user:{id:'fixture-user'},csrf:'fixture-csrf'});}
 if(req.headers.cookie!=='raptor_session=fixture-session')return out({error:'Unauthenticated'},401);
 if(req.method==='POST'&&req.headers['x-csrf-token']!=='fixture-csrf')return out({error:'CSRFRequired'},403);
 if(req.url==='/api/v1/requests'&&req.method==='POST'){const key=req.headers['idempotency-key'];if(keys.has(key))return out(requests.get(keys.get(key)),201);const id='fixture-request-'+ ++creates;assert.equal(body.model,'gpt-5.6-luna');assert.equal(body.envCode,'fixture-env');assert.equal(body.object.code,'fixture-app');const r={id,creatorId:'fixture-user',definition:body,status:'queued'};requests.set(id,r);keys.set(key,id);cancelled=false;return out(r,201);}
 const m=req.url.match(/^\/api\/v1\/requests\/([^/?]+)(.*)$/);if(!m)return out({},404);const r=requests.get(m[1]);if(!r)return out({},404);
 if(m[2]==='/actions'){cancelled=true;return out({accepted:true});}
 if(m[2].startsWith('/events'))return out({events:[],syncUnavailable:false});
 const id=r.id,attempt='fixture-attempt-'+id,stamp=new Date().toISOString(),status=cancelled?'cancelled':hold?'running':'completed';const evidence=[{server:'raptor',tool:'request_get',evidenceMode:'catalog',observedAt:stamp,identity:{requestId:id,envCode:'fixture-env',objectCode:'fixture-app'},state:{}},{server:'infra',tool:'cloud_identity_get',evidenceMode:'live',observedAt:stamp,identity:{envCode:'fixture-env'},state:{accountMatches:true}},...['deployments_list','deployment_status_get'].map(tool=>({server:'infra',tool,evidenceMode:'live',observedAt:stamp,identity:{envCode:'fixture-env',appCode:'fixture-app'},state:{}}))];
 out({request:{...r,status},executionAvailable:true,cancellationPending:false,execution:{requestId:id,attemptId:attempt,status,runtimeMode:'live',updatedAt:stamp,recoveryNeeded:false,checkpointStatus:'verified',cleanupStatus:{sandboxAbsent:true,keyAbsent:true,accessRevoked:true},...(status==='completed'?{result:{requestId:id,attemptId:attempt,selectedModel:'gpt-5.6-luna',actualModel:'gpt-5.6-luna',answer:'Fixture answer',generatedAt:stamp,usage:[{input:1,output:1,totalTokens:2}],evidence}}:{})}});
});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const credentialFile=path.join(root,'credentials.json'),configFile=path.join(root,'config.json');await fs.writeFile(credentialFile,JSON.stringify({username:'fixture',password:'synthetic-password'}),{mode:0o600});await fs.writeFile(configFile,JSON.stringify({origin,applicationCode:'fixture-app',environmentCode:'fixture-env',model:'gpt-5.6-luna',credentialsFile:credentialFile,stateDir:path.join(root,'state'),allowLoopbackHTTP:true}),{mode:0o600});
let proc;const updates=[];async function connect(){proc=spawn(binary,['--config',configFile],{stdio:['pipe','pipe','pipe']});let diagnostic='';proc.stderr.on('data',b=>diagnostic+=b);const connection=new acp.ClientSideConnection(()=>({sessionUpdate:p=>{updates.push(p);},requestPermission:()=>{throw Error('Unexpected permission request');}}),acp.ndJsonStream(Writable.toWeb(proc.stdin),Readable.toWeb(proc.stdout)));const init=await connection.initialize({protocolVersion:1,clientCapabilities:{},clientInfo:{name:'raptor-fixture',version:'1'}});assert.equal(init.protocolVersion,1);assert.equal(init.agentCapabilities.loadSession,true);return connection;}
async function close(){const p=proc;const done=once(p,'exit');p.kill('SIGTERM');await Promise.race([done,new Promise((_,reject)=>setTimeout(()=>reject(Error('SIGTERM failed to exit with stdin open')),2000))]);}
try{let c=await connect();const session=await c.newSession({cwd:root,mcpServers:[{name:'must-not-run',command:'touch',args:[path.join(root,'UNSAFE')],env:[]}]});const id=session.sessionId;const result=await c.prompt({sessionId:id,prompt:[{type:'text',text:'health?'}]});assert.equal(result.stopReason,'end_turn');assert(updates.some(p=>p.update.sessionUpdate==='agent_message_chunk'&&p.update.content.text==='Fixture answer'));assert(updates.some(p=>p.update.sessionUpdate==='tool_call_update'&&p.update.status==='completed'));assert.equal(creates,1);await assert.rejects(fs.stat(path.join(root,'UNSAFE')));
 await close();updates.length=0;c=await connect();await c.loadSession({sessionId:id,cwd:root,mcpServers:[]});assert.equal(creates,1);assert(updates.some(p=>p.update.sessionUpdate==='user_message_chunk'));assert(updates.some(p=>p.update.sessionUpdate==='agent_message_chunk'&&p.update.content.text==='Fixture answer'));
 hold=true;const second=await c.newSession({cwd:root,mcpServers:[]});const pending=c.prompt({sessionId:second.sessionId,prompt:[{type:'text',text:'cancel this'}]});const until=Date.now()+10000;while(creates<2&&Date.now()<until)await new Promise(r=>setTimeout(r,20));assert.equal(creates,2);await c.cancel({sessionId:second.sessionId});assert.equal((await pending).stopReason,'cancelled');assert(cancelled);await close();console.log(JSON.stringify({sdkVersion:'1.7.0',fixture:true,newPrompt:true,reloadWithoutDuplicate:true,cancellation:true,mcpNeverExecuted:true,requests:creates}));
}finally{if(proc&&!proc.killed)proc.kill();await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});}
