export function validateParameters(schema, values) {
  const errors=[];
  for (const name of schema.required ?? []) if (!(name in values) || values[name]==='') errors.push(`${name} is required`);
  for (const [name,value] of Object.entries(values)) {
    const field=schema.properties?.[name];
    if (!field) { errors.push(`${name} is not supported`); continue; }
    if (field.type==='integer' && (!Number.isSafeInteger(value) || value<(field.minimum ?? -Infinity))) errors.push(`${name} must be an integer at least ${field.minimum ?? 0}`);
    if (field.type==='string' && (typeof value!=='string' || Array.from(value).length<(field.minLength ?? 0) || (field.maxLength!==undefined && Array.from(value).length>field.maxLength) || (field.maxBytes!==undefined && new TextEncoder().encode(value).length>field.maxBytes) || (field['x-multiline'] && !value.trim()))) errors.push(`${name} must be text`);
    if (field.enum && !field.enum.includes(value)) errors.push(`${name} must use a listed value`);
  }
  return errors;
}
export function groupEnvironments(envs) { const groups=new Map(); for(const env of envs){if(!groups.has(env.groupCode))groups.set(env.groupCode,[]);groups.get(env.groupCode).push(env);}return groups; }
export function discoveryView(deployments,error){return error?{state:'unavailable',message:'Deployment discovery is unavailable'}:{state:deployments.length?'available':'empty',deployments};}
export function createProgressController({read,schedule=setTimeout,cancel=clearTimeout,onChange=()=>{}}){
  const state={requestId:null,events:[],cursor:0,unavailable:false};let timer,epoch=0;
  async function poll(id,version){try{const result=await read(id,state.cursor);if(version!==epoch||id!==state.requestId)return;const known=new Set(state.events.map(e=>e.sequence));for(const event of result.events??[]){if(!known.has(event.sequence)){state.events.push(event);known.add(event.sequence);state.cursor=Math.max(state.cursor,event.sequence);}}state.unavailable=!!result.syncUnavailable;}catch{if(version!==epoch)return;state.unavailable=true;}if(version!==epoch)return;onChange(state);timer=schedule(()=>poll(id,version),2000);}
  return {state,async select(id){cancel(timer);epoch++;state.requestId=id;state.events=[];state.cursor=0;return poll(id,epoch);},close(){cancel(timer);epoch++;state.requestId=null;}};
}
let csrf='';
export async function api(path,{method='GET',body,headers={}}={}){const response=await fetch('/api/v1'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...headers},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});const result=await response.json();if(!response.ok)throw new Error(result.error?.code??'Unavailable');return result.data;}
function node(tag,text){const el=document.createElement(tag);if(text!==undefined)el.textContent=String(text);return el;}
function button(text,fn){const el=node('button',text);el.type='button';el.addEventListener('click',()=>Promise.resolve(fn()).catch(showError));return el;}
function showError(error){document.getElementById('message').textContent=error.message??'Unavailable';}
export function renderOperationForm(schema){const host=document.getElementById('operation-fields');host.replaceChildren();for(const [name,field]of Object.entries(schema.properties??{})){const label=node('label',`${name}${schema.required?.includes(name)?' *':''}`);let input;if(field.enum){input=node('select');for(const value of field.enum){const option=node('option',value);option.value=value;input.append(option);}}else if(field['x-multiline']){input=node('textarea');input.rows=5;}else{input=node('input');input.type=field.type==='integer'?'number':'text';if(field.minimum!==undefined)input.min=field.minimum;if(field.type==='integer')input.step='1';}input.name=name;input.required=schema.required?.includes(name)??false;if(field.default!==undefined)input.value=field.default;label.append(input);host.append(label);}}
export function renderProgress(events){const host=document.getElementById('progress');host.replaceChildren();for(const event of events){const row=node('div');row.className='event';row.append(node('strong',`${event.evidenceMode??'unverified'} · ${event.kind}`),node('p',event.summary));if(event.details&&Object.keys(event.details).length){const detail=node('details');detail.append(node('summary','Tool / event details'),node('pre',JSON.stringify(event.details,null,2)));row.append(detail);}host.append(row);}}
export function renderExecutionResult(value){
 const $=id=>document.getElementById(id), execution=value.execution??{}, definition=value.request?.definition??{}, result=execution.result;
 $('answer-panel').hidden=!result?.answer;$('answer').textContent=result?.answer??'';
 const counts=Array.isArray(result?.usage)&&result.usage.length?result.usage.reduce((a,u)=>({input:a.input+u.input,output:a.output+u.output,total:a.total+u.totalTokens}),{input:0,output:0,total:0}):null;
 const cleanup=typeof execution.cleanupStatus==='object'&&execution.cleanupStatus!==null?(execution.cleanupStatus.sandboxAbsent===true&&execution.cleanupStatus.keyAbsent===true&&execution.cleanupStatus.accessRevoked===true?'confirmed':'pending — sandbox '+(execution.cleanupStatus.sandboxAbsent?'absent':'unconfirmed')+', key '+(execution.cleanupStatus.keyAbsent?'absent':'unconfirmed')+', Raptor access '+(execution.cleanupStatus.accessRevoked?'revoked':'unconfirmed')):(execution.cleanupStatus??execution.cleanup??'not recorded');
 $('answer-identity').textContent=`${value.executionAvailable===false?'Last saved · ':''}Requested model: ${definition.model??'not recorded'} · Actual model: ${result?.actualModel??'not recorded'} · Selected skills: ${definition.skills?.tag??'not recorded'} (${definition.skills?.commitSha??'not recorded'}) · Applied skills: ${execution.appliedSkills?.tag??'not recorded'} (${execution.appliedSkills?.commitSha??'not recorded'})${value.lastSuccessfulSyncAt?' · Last sync: '+value.lastSuccessfulSyncAt:''}${counts?' · Usage: '+counts.input+' input, '+counts.output+' output, '+counts.total+' total':''}`;
 $('lifecycle').textContent=`Stage: ${execution.stage??'not recorded'} · Checkpoint: ${execution.checkpointStatus??'not recorded'} · Cleanup: ${cleanup}${execution.failureCode?' · Failure: '+execution.failureCode:''}${value.cancellationPending?' · Cancellation requested; waiting for cleanup':''}`;
 $('answer-evidence').replaceChildren();for(const evidence of result?.evidence??[]){$('answer-evidence').append(node('p',`${evidence.evidenceMode??'unverified'} · ${evidence.server}/${evidence.tool} · ${evidence.observedAt??'timestamp not recorded'}`),node('pre',JSON.stringify({identity:evidence.identity,state:evidence.state},null,2)));}
 const question=definition.operations?.some(op=>op.name==='application.question');
 const restricted=question;
 for(const control of document.querySelectorAll?.('[data-action]')??[])control.hidden=restricted&&control.dataset.action!=='cancel';
 if($('skills-change'))$('skills-change').hidden=restricted;
}
export function updateNavigation(panel,tab){
 for(const [id,active] of [['catalog-nav',panel==='catalog-panel'],['requests-nav',panel==='requests-panel'||panel==='request-panel']]){
  const control=document.getElementById(id);
  if(active)control.setAttribute('aria-current','page');else control.removeAttribute('aria-current');
 }
 for(const control of document.querySelectorAll('[data-tab]')){
  if(control.dataset.tab===tab)control.setAttribute('aria-current','page');else control.removeAttribute('aria-current');
 }
}
async function start(){
 const $=id=>document.getElementById(id);let objects=[],envs=[],releases=[],schemas={},selectedObject=null,requestId=null,currentTab='overview',basket=[],viewEpoch=0,requestEpoch=0,pendingSubmission=null;
 const progress=createProgressController({read:(id,cursor)=>api(`/requests/${encodeURIComponent(id)}/events?after=${cursor}`),onChange:state=>{renderProgress(state.events);$('progress-availability').textContent=state.unavailable?'Live sync unavailable; showing saved history':'Checking progress every two seconds';refreshRequest(state.requestId).catch(showError);}});
 function panel(name){updateNavigation(name,currentTab);for(const id of ['catalog-panel','requests-panel','request-panel','login-panel'])$(id).hidden=id!==name;}
 function skillOptions(select){select.replaceChildren();for(const v of releases){const option=node('option',v.tag);option.value=v.tag;select.append(option);}}
 function pickedSkills(select){return releases.find(v=>v.tag===select.value)??{tag:'',commitSha:''};}
 function fillEnvironments(){const select=$('environment');select.replaceChildren();for(const [name,values]of groupEnvironments(envs)){const group=node('optgroup');group.label=name;for(const env of values){const option=node('option',`${env.code} · ${env.stage}`);option.value=env.code;group.append(option);}select.append(group);}}
 async function refreshCatalog(){[objects,envs,schemas]=await Promise.all([api('/objects'),api('/environments'),api('/operation-schemas')]);try{releases=await api('/skills/releases');}catch{releases=[];}fillEnvironments();for(const id of ['request-skills','change-skills'])skillOptions($(id));$('objects').replaceChildren();for(const object of objects)$('objects').append(button(`${object.name} <${object.code}> · ${object.kind}`,()=>openObject(object)));}
 async function openObject(object){progress.close();requestId=null;viewEpoch++;selectedObject=object;panel('catalog-panel');$('object-detail').hidden=false;$('object-heading').textContent=`${object.name} <${object.code}>`;$('operation').replaceChildren();for(const [name,schema]of Object.entries(schemas)){if(schema['x-object-kind']===object.kind){const option=node('option',name);option.value=name;$('operation').append(option);}}$('operation-form').hidden=!$('operation').value;if($('operation').value)renderOperationForm(schemas[$('operation').value]);$('model-field').hidden=$('operation').value!=='application.question';await showDetail();}
 async function showDetail(){const object=selectedObject;if(!object)return;const env=$('environment').value;const token=++viewEpoch;const host=$('detail');host.replaceChildren();
  if(currentTab==='overview'){const form=node('form');const name=node('input');name.value=object.name;name.required=true;const description=node('textarea');description.value=object.description??'';form.append(name,description,node('button','Save catalog metadata'));form.addEventListener('submit',async e=>{e.preventDefault();try{selectedObject=await api(`/objects/${object.id}`,{method:'PATCH',body:{name:name.value,description:description.value}});await refreshCatalog();await openObject(selectedObject);}catch(err){showError(err);}});host.append(node('p','Catalog creation does not deploy infrastructure.'),form);return;}
  if(currentTab==='related'){const requests=await api('/requests');if(token!==viewEpoch)return;for(const r of requests)if(r.definition.object?.code===object.code)host.append(button(`${r.id} · ${r.status}`,()=>loadRequest(r.id)));return;}
  let deployments;try{deployments=await api(`/objects/${object.id}/deployments?env=${encodeURIComponent(env)}`);}catch(err){if(token===viewEpoch)host.append(node('p','Discovery unavailable. This does not mean there are no deployments.'));return;}if(token!==viewEpoch)return;if(!deployments.length){host.append(node('p',`No discovered deployment in ${env}`));return;}
  if(currentTab==='dependencies'){for(const d of deployments)host.append(node('p',d['target-db-code']?`DB proxy target database: ${d['target-db-code']} in ${d.envCode}`:'No dependency association returned by Infra API.'));return;}
  for(const d of deployments){const card=node('section');card.append(node('h3',`${d.namespace??''} ${d.name}`),node('span',`${d.evidenceMode??'unavailable'} · ${d.state}`),node('pre',JSON.stringify(d,null,2)));if(object.kind==='application')card.append(button('Add deployment to restart batch',()=>{const target={appCode:object.code,envCode:env,clusterId:d.clusterId,namespace:d.namespace,name:d.name,uid:d.uid};if(!basket.some(t=>JSON.stringify(t)===JSON.stringify(target)))basket.push(target);renderBasket();}));host.append(card);}
 }
 function renderBasket(){$('basket').replaceChildren();for(const t of basket)$('basket').append(node('p',`${t.appCode}, ${t.envCode}, ${t.namespace}/${t.name}`));}
 async function submit(body){
  const signature=JSON.stringify(body);
  if(pendingSubmission?.promise)return pendingSubmission.promise;
  if(!pendingSubmission || pendingSubmission.signature!==signature)pendingSubmission={signature,key:crypto.randomUUID(),promise:null};
  const pending=pendingSubmission;
  pending.promise=(async()=>{const result=await api('/requests',{method:'POST',body,headers:{'Idempotency-Key':pending.key}});pendingSubmission=null;await loadRequest(result.id);})();
  try{return await pending.promise;}finally{pending.promise=null;}
 }
 async function loadRequest(id){const version=++requestEpoch;progress.close();location.hash='request='+encodeURIComponent(id);requestId=id;panel('request-panel');await refreshRequest(id);if(version!==requestEpoch || requestId!==id)return;await progress.select(id);}
 async function refreshRequest(id){if(!id)return;const token=id;const value=await api(`/requests/${encodeURIComponent(id)}`);if(token!==requestId)return;const request=value.request??value;$('request-heading').textContent=`Request ${request.id}`;$('request-definition').textContent=JSON.stringify(request.definition,null,2);$('request-state').textContent=value.executionAvailable===false?`${request.status} (last saved); Execution sync unavailable`:`${request.status} · ${value.execution?.runtimeMode??'unverified'} execution`;renderExecutionResult(value);$('target-results').replaceChildren();for(const item of value.targets??[]){const row=node('section');row.append(node('p',`${item.target.appCode} · ${item.target.envCode} · ${item.target.namespace}/${item.target.name}: ${item.state} · ${item.details?.evidenceMode??'unverified'}`),node('pre',JSON.stringify(item.details??{},null,2)));$('target-results').append(row);}$('approvals').replaceChildren();for(const approval of value.approvals??[]){const box=node('section');box.append(node('h3',`Approval ${approval.state}`),node('pre',JSON.stringify(approval.binding,null,2)));if(approval.state==='pending'){box.append(button('Approve',()=>decision(id,approval.approvalId,{decision:'approve'})));for(const next of ['block','cancel','continue'])box.append(button(`Deny and ${next}`,()=>decision(id,approval.approvalId,{decision:'deny',next,guidance:$('instructions').value})));}$('approvals').append(box);}if(value.execution?.recoveryNeeded)$('request-state').append(node('p','Recovery required: previous runtime ownership is unresolved. No automatic replay.'));if(value.execution?.appliedSkills)$('request-state').append(node('p',`Applied skills: ${value.execution.appliedSkills.tag??'not started'}`));}
 async function decision(id,approvalId,body){await api(`/requests/${id}/approvals/${approvalId}/decision`,{method:'POST',body});await refreshRequest(id);}
 async function requestList(){progress.close();requestId=null;panel('requests-panel');const list=await api('/requests');$('request-list').replaceChildren();for(const r of list)$('request-list').append(button(`${r.id} · ${r.definition.type} · ${r.status}`,()=>loadRequest(r.id)));}
 $('login').addEventListener('submit',async e=>{e.preventDefault();try{const data=await api('/login',{method:'POST',body:Object.fromEntries(new FormData(e.target))});csrf=data.csrf;$('identity').textContent=data.user.username;await refreshCatalog();panel('catalog-panel');}catch(err){showError(err);}});
 $('logout').onclick=async()=>{try{await api('/logout',{method:'POST'});progress.close();csrf='';panel('login-panel');}catch(e){showError(e);}};
 $('catalog-nav').onclick=()=>{progress.close();requestId=null;panel('catalog-panel');};$('requests-nav').onclick=()=>requestList().catch(showError);$('environment').onchange=()=>showDetail().catch(showError);
 for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{currentTab=b.dataset.tab;updateNavigation('catalog-panel',currentTab);showDetail().catch(showError);};$('operation').onchange=()=>{renderOperationForm(schemas[$('operation').value]);$('model-field').hidden=$('operation').value!=='application.question';};
 $('create-object').onsubmit=async e=>{e.preventDefault();try{const object=await api('/objects',{method:'POST',body:Object.fromEntries(new FormData(e.target))});await refreshCatalog();await openObject(object);}catch(err){showError(err);}};
 $('operation-form').onsubmit=async e=>{e.preventDefault();try{const name=$('operation').value,schema=schemas[name],parameters={};for(const input of $('operation-fields').querySelectorAll('input,select,textarea')){if(input.value==='')continue;parameters[input.name]=schema.properties[input.name].type==='integer'?Number(input.value):input.value;}const errors=validateParameters(schema,parameters);if(errors.length)throw new Error(errors.join('; '));await submit({type:'agent',object:{kind:selectedObject.kind,code:selectedObject.code},envCode:$('environment').value,operations:[{name,parameters}],skills:pickedSkills($('request-skills')),...(name==='application.question'?{model:$('request-model').value}:{})});}catch(err){showError(err);}};
 $('restart-submit').onclick=()=>{if(!basket.length){showError(new Error('Choose deployments first'));return;}submit({type:'direct',operation:'application.restart',targets:basket}).catch(showError);};$('restart-clear').onclick=()=>{basket=[];renderBasket();};
 for(const b of document.querySelectorAll('[data-action]'))b.onclick=async()=>{try{await api(`/requests/${requestId}/actions`,{method:'POST',body:{action:b.dataset.action,instructions:$('instructions').value}});await refreshRequest(requestId);}catch(err){showError(err);}};
 $('skills-change').onsubmit=async e=>{e.preventDefault();try{await api(`/requests/${requestId}/skills`,{method:'POST',body:{...pickedSkills($('change-skills')),strategy:e.target.elements.strategy.value}});await refreshRequest(requestId);}catch(err){showError(err);}};
 window.addEventListener('pagehide',()=>progress.close());
 try{const session=await api('/session');csrf=session.csrf;$('identity').textContent=session.user.username;await refreshCatalog();const saved=location.hash.match(/^#request=(.+)$/);if(saved){await loadRequest(decodeURIComponent(saved[1]));}else{panel('catalog-panel');}}catch{panel('login-panel');}
}
if(typeof document!=='undefined')start().catch(showError);
