import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {runLiveJob} from './live-runner.mjs';
import {validateLiveRequest} from './live-contract.mjs';

function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'raptor-model-'));const state=path.join(root,'state'),privateRoot=path.join(root,'private');fs.mkdirSync(state);fs.mkdirSync(privateRoot);const old={type:'oauth',access:'old-access',refresh:'old-refresh',expires:Date.now()+3600000},leased={...old,access:'leased-access',refresh:'leased-refresh'};fs.writeFileSync(path.join(state,'auth.json'),JSON.stringify({'openai-codex':old}),{mode:0o600});fs.writeFileSync(path.join(privateRoot,'model-credential.json'),JSON.stringify({'openai-codex':leased}),{mode:0o600});return {root,state,privateRoot,old,leased,job:{state_root:state,private_root:privateRoot,mount_root:'/unused',prefix:'unused',generation:'test',request:{binding:{providerId:'codex'},question:'hello'},limits:{},mcp:{}}}}

test('Codex model refresh must publish before checkpoint',async()=>{const f=fixture();try{let checkpointed=false;const next={...f.leased,access:'new-access',refresh:'new-refresh'};const timer=setInterval(()=>{if(fs.existsSync(path.join(f.privateRoot,'model-refresh.json'))){const wire=JSON.parse(fs.readFileSync(path.join(f.privateRoot,'model-refresh.json')));assert.deepEqual(wire.credential,next);fs.writeFileSync(path.join(f.privateRoot,'model-refresh-ack.json'),JSON.stringify({status:'published',generation:2}),{mode:0o600});clearInterval(timer)}},10);
 const result=await runLiveJob(f.job,{loadPiRuntime:async({provider})=>{assert.equal(provider,'openai-codex');assert.equal(JSON.parse(fs.readFileSync(path.join(f.state,'auth.json')))['openai-codex'].access,'leased-access');return {runtime:{}}},runLiveAppQuestion:async()=>{fs.writeFileSync(path.join(f.state,'auth.json'),JSON.stringify({'openai-codex':next}));return {passed:true}},createCheckpoint:async()=>{checkpointed=true;assert.equal(fs.existsSync(path.join(f.privateRoot,'model-refresh-ack.json')),true);return {archive_key:'ok'}}});assert.equal(result.passed,true);assert.equal(checkpointed,true);clearInterval(timer)}finally{fs.rmSync(f.root,{recursive:true,force:true})}});

test('unconfirmed Codex refresh blocks checkpoint',async()=>{const f=fixture();try{let checkpointed=false;const controller=new AbortController();setTimeout(()=>controller.abort(),50);const result=await runLiveJob(f.job,{signal:controller.signal,loadPiRuntime:async()=>({runtime:{}}),runLiveAppQuestion:async()=>{fs.writeFileSync(path.join(f.state,'auth.json'),JSON.stringify({'openai-codex':{...f.old,refresh:'rotated'}}));return {passed:true}},createCheckpoint:async()=>{checkpointed=true}});assert.equal(result.error,'CredentialRefreshUnconfirmed');assert.equal(checkpointed,false)}finally{fs.rmSync(f.root,{recursive:true,force:true})}});

test('Codex refresh is published even when inference throws',async()=>{const f=fixture();let timer;try{const next={...f.leased,refresh:'rotated-after-error'};timer=setInterval(()=>{if(fs.existsSync(path.join(f.privateRoot,'model-refresh.json'))){fs.writeFileSync(path.join(f.privateRoot,'model-refresh-ack.json'),JSON.stringify({status:'published',generation:2}),{mode:0o600});clearInterval(timer)}},10);const result=await runLiveJob(f.job,{loadPiRuntime:async()=>({runtime:{}}),runLiveAppQuestion:async()=>{fs.writeFileSync(path.join(f.state,'auth.json'),JSON.stringify({'openai-codex':next}));throw Error('private inference error')},createCheckpoint:async()=>({archive_key:'ok'})});assert.equal(result.error,'RunnerFailed');assert.equal(result.passed,false);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(f.privateRoot,'model-refresh.json'))).credential,next)}finally{clearInterval(timer);fs.rmSync(f.root,{recursive:true,force:true})}});

test('selected Codex model binding rejects missing connection version',()=>{const b={requestId:'11111111-1111-1111-1111-111111111111',attemptId:'22222222-2222-2222-2222-222222222222',operation:'application.question',objectKind:'application',objectCode:'app',envCode:'dev',skillsCommit:'a'.repeat(40),model:'gpt-6-sol',providerId:'codex'};assert.throws(()=>validateLiveRequest({binding:b,question:'health?'}),/InvalidJob/);assert.equal(validateLiveRequest({binding:{...b,connectionVersion:2},question:'health?'}).binding.model,'gpt-6-sol')});
