import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {loadPiRuntime} from './pi-adapter.mjs';import {operationCapabilities,operationToolSchema} from './operation-profile.mjs';
import {OBSERVATION_TOOLS} from './observation-extension.mjs';
import {runLiveReplacement} from './live-replacement.mjs';
for (const waitKind of ['approval','resource','error']) test(waitKind==='error'?'real pinned Pi provider error stays explicit':'real pinned Pi settles '+waitKind+' pause with no subsequent model call',async()=>{
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'pi-pause-')));try{
 const state=path.join(root,'state'),skills=path.join(root,'skills');fs.mkdirSync(state);fs.mkdirSync(path.join(skills,'pgcat-replacement'),{recursive:true});fs.writeFileSync(path.join(skills,'pgcat-replacement','SKILL.md'),'---\nname: pgcat-replacement\ndescription: Replace scoped PgCat nodes safely.\n---\nRequest approval before scale-in.\n');fs.writeFileSync(path.join(state,'auth.json'),JSON.stringify({openai:{type:'oauth',access:'synthetic',refresh:'synthetic',expires:Date.now()+999999}}));
 const b={requestId:'11111111-1111-4111-8111-111111111111',attemptId:'22222222-2222-4222-8222-222222222222',definitionSha256:'a'.repeat(64),skillsCommit:'b'.repeat(40),operation:'db-proxy.replace-nodes',objectKind:'db-proxy',objectCode:'proxy',envCode:'dev',clusterId:'cluster',model:'gpt-5.6-luna'};
 const scope={envCode:'dev',proxyCode:'proxy',groupId:'group',serverGroupId:'backend',targetDbCode:'db',application:{envCode:'dev',appCode:'client',clusterId:'cluster',namespace:'test',name:'traffic',uid:'uid'}};
 const approvalArgs={requestId:b.requestId,actionId:'scale-three',interface:'ess.scale-in',envCode:'dev',target:{proxyCode:'proxy',groupId:'group'},parameters:{desiredCapacity:3}};
 const entry=new URL(import.meta.resolve('@earendil-works/pi-coding-agent'));const {createAssistantMessageEventStream}=await import(new URL('../node_modules/@earendil-works/pi-ai/dist/utils/event-stream.js',entry));const {runtime}=await loadPiRuntime({stateRoot:state});runtime.getAuth=async()=>({type:'oauth',access:'fixture'});let calls=0;
 runtime.streamSimple=(model,context)=>{assert.ok(OBSERVATION_TOOLS.every(name=>context.messages.some(message=>message.toolsAdded?.some(t=>t.name===name))));calls++;const tool=calls===1?'request_get':calls===2?'approval_request':'request_pause';const args=calls===1?{requestId:b.requestId}:calls===2?approvalArgs:{requestId:b.requestId,reason:'waiting_approval'};const stream=createAssistantMessageEventStream();const message={role:'assistant',content:[{type:'toolCall',id:'call-'+calls,name:waitKind==='resource'?'resource_wait':'mcp__raptor__'+tool,arguments:waitKind==='resource'?{seconds:60}:args}],api:model.api,provider:model.provider,model:model.id,usage:{input:3,output:2,totalTokens:5,cacheRead:0,cacheWrite:0,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:waitKind==='error'?'error':'toolUse',timestamp:Date.now()};stream.push({type:'done',reason:'toolUse',message});return stream;};
 const fetcher=async(url,init)=>{const rpc=JSON.parse(init.body),server=String(url).includes('raptor')?'raptor':'infra';if(rpc.method==='notifications/initialized')return new Response(null,{status:202});let result;if(rpc.method==='initialize')result={protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:server,version:'1'}};else if(rpc.method==='tools/list')result={tools:operationCapabilities(b,scope)[server].map(name=>({name,description:'Scoped operation',inputSchema:operationToolSchema(server,name)}))};else if(rpc.method==='tools/call'){const name=rpc.params.name;const data=name==='request_get'?{requestId:b.requestId,definition:{object:{kind:'db-proxy',code:'proxy'},envCode:'dev',operations:[{name:b.operation}]}}:name==='approval_request'?{requestId:b.requestId,approvalId:'33333333-3333-4333-8333-333333333333',actionId:'scale-three',binding:approvalArgs,state:'pending'}:{accepted:true};result={structuredContent:{data},content:[{type:'text',text:JSON.stringify({data})}]};}else throw Error('UnexpectedRPC');return new Response(JSON.stringify({jsonrpc:'2.0',id:rpc.id,result}),{headers:{'Content-Type':'application/json'}});};
 const out=await runLiveReplacement({stateRoot:state,privateRoot:path.join(root,'private'),runtime,binding:b,replacementScope:scope,observer:{cloudRead:async()=>({}),deploymentRead:async()=>({}),metricsRead:async()=>({}),dbConnectionProbe:async()=>({})},skills:{tag:'skills-v1.0.0',commitSHA:b.skillsCommit,path:skills},limits:{model_seconds:90,max_turns:10,max_output_tokens:1024},mcpConfig:{raptor:{url:'https://raptor.fixture/mcp',headers:{Authorization:'Bearer synthetic'}},infra:{url:'https://infra.fixture/mcp',headers:{'X-Infra-Authorization':'Bearer synthetic'}}},fetch:fetcher});
 if(waitKind==='error'){assert.equal(out.error,'ModelFailed',JSON.stringify(out));assert.equal(out.passed,false);return;}
 assert.equal(out.paused?.kind,waitKind,JSON.stringify(out));assert.equal(out.paused?.approvalId,waitKind==='resource'?'':'33333333-3333-4333-8333-333333333333',JSON.stringify(out));assert.equal(out.error,undefined);assert.equal(out.passed,false);assert.equal(calls,waitKind==='resource'?1:3);assert.equal(out.sessionReference.requestId,b.requestId);assert.equal(out.usage.length,calls);
 const history=fs.readFileSync(path.join(state,'sessions',out.sessionReference.file),'utf8');
 const entries=history.trim().split('\n').map(line=>JSON.parse(line));
 const results=entries.filter(entry=>entry.type==='message'&&entry.message?.role==='toolResult');
 assert.equal(results.length,calls,'all completed tool results must survive the pause');
 assert.equal(results.at(-1).message.toolName,waitKind==='resource'?'resource_wait':'mcp__raptor__request_pause');
 assert.equal(entries.some(entry=>entry.message?.stopReason==='aborted'),false,'pause must settle without synthetic aborted history');
 let resumedCalls=0;
 runtime.streamSimple=model=>{resumedCalls++;const stream=createAssistantMessageEventStream();const message={role:'assistant',content:[{type:'text',text:'Inspecting the approved exact action.'}],api:model.api,provider:model.provider,model:model.id,usage:{input:3,output:2,totalTokens:5,cacheRead:0,cacheWrite:0,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:'stop',timestamp:Date.now()};stream.push({type:'done',reason:'stop',message});return stream;};
 const resumed=await runLiveReplacement({stateRoot:state,privateRoot:path.join(root,'private-resume'),runtime,binding:{...b,attemptId:'44444444-4444-4444-8444-444444444444'},replacementScope:scope,observer:{cloudRead:async()=>({}),deploymentRead:async()=>({}),metricsRead:async()=>({}),dbConnectionProbe:async()=>({})},skills:{tag:'skills-v1.0.0',commitSHA:b.skillsCommit,path:skills},limits:{model_seconds:90,max_turns:10,max_output_tokens:1024},mcpConfig:{raptor:{url:'https://raptor.fixture/mcp',headers:{Authorization:'Bearer fresh-synthetic'}},infra:{url:'https://infra.fixture/mcp',headers:{'X-Infra-Authorization':'Bearer synthetic'}}},fetch:fetcher,sessionReference:out.sessionReference,decisionContext:{approvalId:out.paused.approvalId,actionId:out.paused.actionId,decision:'resume'}});
 assert.equal(resumedCalls,1);assert.equal(resumed.error,'MissingEvidence','ordinary text must not claim replacement completion');
 const continued=fs.readFileSync(path.join(state,'sessions',out.sessionReference.file),'utf8').trim().split('\n').map(line=>JSON.parse(line));
 assert.equal(continued.filter(entry=>entry.message?.role==='toolResult').length,calls,'resume must retain the completed pause round');
 assert.equal(continued.filter(entry=>entry.message?.role==='user').length,2,'resume must append to the same session');

 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
