import {loadPiRuntime} from './pi-adapter.mjs';import {runLiveAppQuestion} from './live-question.mjs';import {createCheckpoint} from './checkpoint.mjs';import fs from 'node:fs';import path from 'node:path';
function currentCodexCredential(stateRoot){const data=JSON.parse(fs.readFileSync(path.join(stateRoot,'auth.json'),'utf8'));const value=data['openai-codex'];if(value?.type!=='oauth'||!value.access||!value.refresh||!Number.isFinite(value.expires))throw Error('NeedsSignIn');return value}
function injectCodexCredential(stateRoot,privateRoot){const stage=path.join(privateRoot,'model-credential.json'),target=path.join(stateRoot,'auth.json');const raw=fs.readFileSync(stage,'utf8'),value=JSON.parse(raw)?.['openai-codex'];if(value?.type!=='oauth'||!value.access||!value.refresh||!Number.isFinite(value.expires))throw Error('NeedsSignIn');if(fs.existsSync(target)&&fs.lstatSync(target).isSymbolicLink())throw Error('InvalidJob');fs.writeFileSync(target,JSON.stringify({'openai-codex':value}),{mode:0o600});fs.chmodSync(target,0o600);fs.unlinkSync(stage)}
async function publishRefresh(privateRoot,credential,signal){const update=path.join(privateRoot,'model-refresh.json'),ack=path.join(privateRoot,'model-refresh-ack.json');fs.writeFileSync(update,JSON.stringify({credential}),{flag:'wx',mode:0o600});const deadline=Date.now()+20000;while(Date.now()<deadline&&!signal?.aborted){if(fs.existsSync(ack)){const value=JSON.parse(fs.readFileSync(ack,'utf8'));if(value.status==='published'&&Number.isSafeInteger(value.generation))return;break}await new Promise(resolve=>setTimeout(resolve,100))}throw Error('CredentialRefreshUnconfirmed')}
import {readObservationConfig,removeObservationCredentials} from './observation-config.mjs';
import {createObservationTools} from './observation-tools.mjs';
import {stageSkillsBundle} from './skills-bundle.mjs';
import {runLiveReplacement} from './live-replacement.mjs';
export async function runLiveJob(job,dependencies={}){
 const deps={loadPiRuntime,runLiveAppQuestion,runLiveReplacement,createCheckpoint,removeObservationCredentials,...dependencies};let settled={passed:false,error:'RunnerFailed'};
 try{
  let observer;if(job.observation_config_path){const config=readObservationConfig(job.observation_config_path,job.private_root);observer=createObservationTools({binding:job.request.binding,config,replacementScope:job.replacement_scope});}
  let skills=job.prepared_skills;if(job.skills_bundle_path){if(job.skills_bundle_path!==job.private_root+'/skills-bundle.json')throw Error('InvalidJob');skills=stageSkillsBundle({file:job.skills_bundle_path,destination:job.private_root+'/skills',binding:job.request.binding});if(skills.tag!==job.skills_release?.tag||skills.commitSHA!==job.skills_release?.commitSha)throw Error('InvalidSkillsRelease');}
  const codex=job.request?.binding?.providerId==='codex';if(codex)injectCodexCredential(job.state_root,job.private_root);const before=codex?currentCodexCredential(job.state_root):null;
  try{const {runtime}=await deps.loadPiRuntime({stateRoot:job.state_root,provider:codex?'openai-codex':'openai'});const replacement=job.request?.binding?.operation==='db-proxy.replace-nodes';settled=await (replacement?deps.runLiveReplacement:deps.runLiveAppQuestion)({binding:job.request?.binding,replacementScope:job.replacement_scope,observer,skills,decisionContext:job.decision_context,stateRoot:job.state_root,privateRoot:job.private_root,runtime,limits:job.limits,request:job.request,mcpConfig:job.mcp,onProgress:dependencies.onProgress,signal:dependencies.signal,sessionReference:job.session_reference,conversation:job.conversation});}
  catch(e){settled={passed:false,error:e.message==='NeedsSignIn'?'NeedsSignIn':'RunnerFailed'};}
  if(codex){const after=currentCodexCredential(job.state_root);if(JSON.stringify(before)!==JSON.stringify(after))await publishRefresh(job.private_root,after,dependencies.signal);}
 }catch(e){if(job.observation_config_path){try{deps.removeObservationCredentials(job.private_root);}catch{return {phase:'live-inference',passed:false,error:'ObservationCleanupFailed'};}}return {phase:'live-inference',passed:false,error:['NeedsSignIn','CredentialRefreshUnconfirmed'].includes(e.message)?e.message:'RunnerFailed'};}
 try{if(job.observation_config_path)deps.removeObservationCredentials(job.private_root);const checkpoint=await deps.createCheckpoint({stateRoot:job.state_root,mountRoot:job.mount_root,generation:job.generation,prefix:job.prefix});return {phase:'live-inference',...settled,checkpoint};}
 catch{const {paused,...failed}=settled;return {phase:'live-inference',...failed,passed:false,error:settled.error??'CheckpointFailed',checkpointError:'CheckpointFailed'};}
}
