import path from 'node:path';import {TOOL_NAMES} from './progress.mjs';
const catalogs={raptor:['request_get','environment_get','object_get'],infra:['cloud_identity_get','deployments_list','deployment_status_get']};
function checkSelectors(server,tool,args,b,discovered){const shapes={request_get:{requestId:b.requestId},environment_get:{requestId:b.requestId,envCode:b.envCode},object_get:{requestId:b.requestId,kind:b.objectKind,code:b.objectCode},cloud_identity_get:{envCode:b.envCode},deployments_list:{envCode:b.envCode,kind:b.objectKind,code:b.objectCode},deployment_status_get:{envCode:b.envCode,appCode:b.objectCode}};const required=shapes[tool];if(!catalogs[server]?.includes(tool)||!args||typeof args!=='object'||Array.isArray(args)||Object.entries(required).some(([k,v])=>args[k]!==v))throw Error('ScopeMismatch');const keys=tool==='deployment_status_get'?[...Object.keys(required),'clusterId','namespace','name','uid']:Object.keys(required);if(Object.keys(args).sort().join(',')!==keys.sort().join(','))throw Error('ScopeMismatch');if(tool==='deployment_status_get'&&!discovered.has(JSON.stringify([args.clusterId,args.namespace,args.name,args.uid])))throw Error('IdentityChanged');}
async function boundedText(response){const reader=response.clone().body?.getReader();if(!reader)return '';const parts=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>65536){void reader.cancel();void response.body?.cancel();throw Error('InvalidMcpResponse');}parts.push(Buffer.from(value));}return Buffer.concat(parts).toString('utf8');}finally{reader.releaseLock();}}
function rpcResponse(text,type){if(type.includes('application/json'))return JSON.parse(text);if(type.includes('text/event-stream')){for(const block of text.split(/\r?\n\r?\n/)){const data=block.split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trimStart()).join('\n');if(data){const v=JSON.parse(data);if(v.result!==undefined||v.error)return v;}}}throw Error('InvalidMcpResponse');}
function observed(server,tool,data,b,discovered,args){const timestamp=()=>new Date().toISOString();if(server==='raptor'){if(tool==='request_get'){const d=data?.definition;if(data?.requestId!==b.requestId||d?.object?.kind!==b.objectKind||d?.object?.code!==b.objectCode||d?.envCode!==b.envCode)throw Error('ScopeMismatch');}return [{server,tool,observedAt:timestamp(),evidenceMode:'catalog',identity:{requestId:b.requestId,objectCode:b.objectCode,envCode:b.envCode},state:{available:true}}];}
 const stamp=v=>{if(v?.evidenceMode!=='live'||typeof v.observedAt!=='string'||!Number.isFinite(Date.parse(v.observedAt)))throw Error('InvalidEvidence');return v.observedAt;};
 if(tool==='cloud_identity_get'){if(data?.envCode!==b.envCode||data?.accountMatches!==true)throw Error('ScopeMismatch');return [{server,tool,observedAt:stamp(data),evidenceMode:'live',identity:{envCode:b.envCode},state:{accountMatches:true}}];}
 const identity=v=>{const id={envCode:v.envCode,objectCode:v.objectCode??v.appCode,clusterId:v.clusterId,namespace:v.namespace,name:v.name,uid:v.uid};if(id.envCode!==b.envCode||id.objectCode!==b.objectCode||['clusterId','namespace','name','uid'].some(k=>typeof id[k]!=='string'||!id[k]))throw Error('IdentityChanged');return id;};
 if(tool==='deployments_list'){if(!Array.isArray(data)||data.length>64)throw Error('InvalidEvidence');return data.map(v=>{const id=identity(v);discovered.add(JSON.stringify([id.clusterId,id.namespace,id.name,id.uid]));return {server,tool,observedAt:stamp(v),evidenceMode:'live',identity:id,state:{state:String(v.state??'unknown').slice(0,256)}};});}
 const id=identity(data);if(['clusterId','namespace','name','uid'].some(key=>id[key]!==args?.[key]))throw Error('IdentityChanged');if(!discovered.has(JSON.stringify([id.clusterId,id.namespace,id.name,id.uid])))throw Error('IdentityChanged');const state={};for(const k of ['generation','observedGeneration','replicas','updatedReplicas','readyReplicas']){if(!Number.isSafeInteger(data[k])||data[k]<0)throw Error('InvalidEvidence');state[k]=data[k];}return [{server,tool,observedAt:stamp(data),evidenceMode:'live',identity:id,state}];
}
export function createGuardedFetch({server,url,binding,fetch:fetcher=globalThis.fetch,onCatalog=()=>{},onEvidence=()=>{},discovered=new Set(),knownSecrets=[]}){const endpoint=new URL(url);if(endpoint.protocol!=='https:'||endpoint.username||endpoint.password||endpoint.hash||!catalogs[server])throw Error('InvalidMcpConfiguration');return async(input,init={})=>{const target=new URL(String(input));if(target.href!==endpoint.href)throw Error('McpOriginMismatch');if(init.method==='DELETE')return new Response('',{status:405});if(init.method!=='POST'||typeof init.body!=='string'||Buffer.byteLength(init.body)>8192)throw Error('InvalidMcpMethod');const rpc=JSON.parse(init.body);if(!['initialize','notifications/initialized','tools/list','tools/call','ping'].includes(rpc.method))throw Error('InvalidMcpMethod');if(rpc.method==='tools/call')checkSelectors(server,rpc.params?.name,rpc.params?.arguments,binding,discovered);const response=await fetcher(input,{...init,redirect:'error'});if(response.status>=300&&response.status<400)throw Error('McpRedirectRejected');if(!response.ok)return new Response('McpRequestFailed',{status:response.status,headers:{'Content-Type':'application/json'}});if(rpc.id===undefined)return response;const text=await boundedText(response);if(knownSecrets.some(secret=>secret&&text.includes(secret)))throw Error('SensitiveMcpResponse');const message=rpcResponse(text,response.headers.get('content-type')??'');if(message.error)return new Response(JSON.stringify({jsonrpc:'2.0',id:rpc.id,error:{code:-32603,message:'McpRequestFailed'}}),{headers:{'Content-Type':'application/json'}});if(rpc.method==='tools/call'&&message.result?.isError)return new Response(JSON.stringify({jsonrpc:'2.0',id:rpc.id,result:{isError:true,content:[{type:'text',text:'McpToolFailed'}]}}),{headers:{'Content-Type':'application/json'}});if(rpc.method==='tools/list'){const names=message.result?.tools?.map(t=>t.name).sort();if(!names||names.join(',')!==[...catalogs[server]].sort().join(','))throw Error('UnexpectedToolCatalog');onCatalog(server);}if(rpc.method==='tools/call'&&!message.result?.isError){const result=message.result;let envelope=result.structuredContent;if(!envelope){const item=result.content?.find(x=>x.type==='text');if(!item)throw Error('InvalidEvidence');envelope=JSON.parse(item.text);}onEvidence(observed(server,rpc.params.name,envelope?.data,binding,discovered,rpc.params.arguments));}return response;};}
export async function createScopedMcpRuntime({sdk,stateRoot,privateRoot,servers,binding,fetch:fetcher,onEvidence}){
 if(Object.keys(servers??{}).sort().join(',')!=='infra,raptor')throw Error('InvalidMcpConfiguration');const {StreamableHttpTransport}=await import('@earendil-works/pi-mcp');const catalogsReady=new Set(),discovered=new Set(),transports=[];
 const config={servers:['raptor','infra'].map(name=>({name,source:'request-bound-controller',scope:'extension',config:{url:servers[name].url,headers:servers[name].headers,exposure:'direct',timeout:25}})),autoEnableCodemode:false,errors:[]};
 const extension=sdk.createMcpExtension({loadConfig:()=>config,logPath:path.join(privateRoot,'mcp.log'),startupWaitMs:10000,openUrl:()=>{throw Error('NeedsSignIn');},updateConfig:()=>{throw Error('ImmutableMcpConfiguration');},createTransport:entry=>{const transport=new StreamableHttpTransport({url:entry.config.url,headers:entry.config.headers,openGetStream:false,maxMessageBytes:65536,reconnect:{maxRetries:0},fetch:createGuardedFetch({server:entry.name,url:entry.config.url,binding,fetch:fetcher,onCatalog:name=>catalogsReady.add(name),onEvidence,discovered,knownSecrets:credentialValues(entry.config.headers)})});transports.push(transport);return transport;}});
 return {extension,async ready(session){const deadline=Date.now()+10000;while(Date.now()<deadline){if(catalogsReady.size===2&&TOOL_NAMES.every(t=>session.getAllTools().some(v=>v.name===t))){session.setActiveToolsByName(TOOL_NAMES);if(session.getActiveToolNames().sort().join(',')!==[...TOOL_NAMES].sort().join(','))throw Error('UnexpectedToolCatalog');return;}await new Promise(resolve=>setTimeout(resolve,20));}throw Error('McpUnavailable');},async dispose(){await Promise.allSettled(transports.map(t=>t.close()));}};
}

export function credentialValues(headers){return Object.values(headers??{}).flatMap(value=>{const out=[value];if(value.startsWith('Bearer '))out.push(value.slice(7));if(value.startsWith('Basic ')){const encoded=value.slice(6),plain=Buffer.from(encoded,'base64').toString('utf8'),colon=plain.indexOf(':');out.push(encoded,plain);if(colon>=0)out.push(plain.slice(colon+1));}return out.filter(Boolean);});}
