package admin

const environmentPanel = `<section class="section" id="groups-section"><h2>Environment groups</h2><p class="section-desc">Organize deployment environments under a platform group.</p><form id="group-form"><div class="grid two"><label class="field">Group code<input name="code" required placeholder="raptor"></label><label class="field">Group name<input name="name" required placeholder="Raptor"></label></div><div class="actions"><button class="button">Create group</button></div></form><h3>Groups</h3><div id="group-list" class="data-list" aria-live="polite"></div></section><section class="section" id="environments-section"><h2>Environments</h2><p class="section-desc">Manage cloud targets and source repositories for each stage.</p><form id="env-form"><div class="grid"><label class="field">Code<input name="code" required></label><label class="field">Group code<input name="groupCode" required></label><label class="field">Stage<input name="stage" required></label><label class="field">Cloud<input name="cloud"></label><label class="field">Region<input name="region"></label><label class="field">Cloud account ID<input name="accountId"></label><label class="field">ACK cluster ID<input name="ackClusterId"></label></div><h3>Repositories</h3><div id="repository-rows" class="repo-rows"></div><div class="actions"><button class="button secondary" type="button" id="add-repository">Add repository</button></div><div class="actions"><label class="check"><input name="edit" type="checkbox">Update an existing environment</label><button class="button">Save environment</button></div></form><h3>Configured environments</h3><div id="environment-list" class="data-list" aria-live="polite"></div></section>`
const environmentScript = `<script>
let environments=[];
function renderRows(id,items,kind){const root=document.getElementById(id);root.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='empty';p.textContent='No '+kind+' yet.';root.append(p);return}for(const item of items){const row=document.createElement('div');row.className='data-row';const code=document.createElement('strong');code.textContent=item.code||'Unnamed';const detail=document.createElement('span');detail.textContent=kind==='groups'?(item.name||''):[item.groupCode,item.stage,item.cloud,item.region].filter(Boolean).join(' / ');row.append(code,detail);root.append(row)}}
async function refreshEnvironments(){const [groups,envs]=await Promise.all([api('environment-groups'),api('environments')]);environments=envs;renderRows('group-list',groups,'groups');renderRows('environment-list',envs,'environments')}
document.getElementById('group-form').onsubmit=safely(async e=>{await api('environment-groups','POST',Object.fromEntries(new FormData(e.target)));e.target.reset();await refreshEnvironments();document.getElementById('notice').textContent='Group created.'});
const envForm=document.getElementById('env-form');
const repoRows=document.getElementById('repository-rows');
function addRepository(repo={}){const row=document.createElement('fieldset');const branchRequired=!repo.url||!!repo.baseBranch;row.innerHTML='<legend>Repository</legend><label class="field">Purpose<select name="purpose"><option value="terraform">Terraform</option><option value="kubernetes">Kubernetes</option></select></label><label class="field">HTTPS GitHub URL<input name="url" type="url" required></label><label class="field">Base branch<input name="baseBranch"'+(branchRequired?' required':'')+'></label><label class="field">Directory<input name="directory" required></label><button class="button secondary" type="button">Remove repository</button>';row.querySelector('[name="purpose"]').value=repo.purpose||'terraform';for(const key of ['url','baseBranch','directory'])row.querySelector('[name="'+key+'"]').value=repo[key]||'';row.querySelector('button').onclick=()=>row.remove();repoRows.append(row)}
document.getElementById('add-repository').onclick=()=>addRepository();
function fillEnvironment(){if(!envForm.elements.edit.checked)return;const current=environments.find(x=>x.code===envForm.elements.code.value);if(!current)return;for(const key of ['groupCode','stage','cloud','region','accountId','ackClusterId'])envForm.elements[key].value=current[key]||'';repoRows.replaceChildren();for(const repo of current.repositories||[])addRepository(repo)}
envForm.elements.edit.onchange=fillEnvironment;envForm.elements.code.onchange=fillEnvironment;
envForm.onsubmit=safely(async e=>{const f=new FormData(e.target);const v={code:f.get('code'),groupCode:f.get('groupCode'),stage:f.get('stage'),cloud:f.get('cloud'),region:f.get('region'),accountId:f.get('accountId'),ackClusterId:f.get('ackClusterId'),repositories:[]};for(const row of repoRows.children){const field=name=>row.querySelector('[name="'+name+'"]').value.trim();v.repositories.push({purpose:field('purpose'),url:field('url'),baseBranch:field('baseBranch'),directory:field('directory')})}await api('environments'+(f.has('edit')?'/'+encodeURIComponent(v.code):''),f.has('edit')?'PATCH':'POST',v);await refreshEnvironments();document.getElementById('notice').textContent='Environment saved.'});
refreshEnvironments().catch(()=>{});
</script>`
