package admin

const environmentPanel = `<h2>Environment groups</h2><form id="group-form"><input name="code" placeholder="Group code" required><input name="name" placeholder="Group name" required><button>Create group</button></form><h2>Environments</h2><form id="env-form"><label>Code<input name="code" required></label><label>Group code<input name="groupCode" required></label><label>Stage<input name="stage" required></label><label>Cloud<input name="cloud"></label><label>Region<input name="region"></label><label>Cloud account ID<input name="accountId"></label><label>ACK cluster ID<input name="ackClusterId"></label><div id="repository-rows"></div><button type="button" id="add-repository">Add repository</button><label><input name="edit" type="checkbox">Edit existing environment</label><button>Save environment</button></form><pre id="environment-list"></pre>`
const environmentScript = `<script>
let environments=[];
async function refreshEnvironments(){const [groups,envs]=await Promise.all([api('environment-groups'),api('environments')]);environments=envs;document.getElementById('environment-list').textContent=JSON.stringify({groups,environments:envs},null,2)}
document.getElementById('group-form').onsubmit=safely(async e=>{await api('environment-groups','POST',Object.fromEntries(new FormData(e.target)));e.target.reset();await refreshEnvironments()});
const envForm=document.getElementById('env-form');
const repoRows=document.getElementById('repository-rows');
function addRepository(repo={}){const row=document.createElement('fieldset');const branchRequired=!repo.url||!!repo.baseBranch;row.innerHTML='<legend>Repository</legend><label>Purpose<select name="purpose"><option value="terraform">Terraform</option><option value="kubernetes">Kubernetes</option></select></label><label>HTTPS GitHub URL<input name="url" type="url" required></label><label>Base branch<input name="baseBranch"'+(branchRequired?' required':'')+'></label><label>Directory<input name="directory" required></label><button type="button">Remove repository</button>';row.querySelector('[name="purpose"]').value=repo.purpose||'terraform';for(const key of ['url','baseBranch','directory'])row.querySelector('[name="'+key+'"]').value=repo[key]||'';row.querySelector('button').onclick=()=>row.remove();repoRows.append(row)}
document.getElementById('add-repository').onclick=()=>addRepository();
function fillEnvironment(){if(!envForm.elements.edit.checked)return;const current=environments.find(x=>x.code===envForm.elements.code.value);if(!current)return;for(const key of ['groupCode','stage','cloud','region','accountId','ackClusterId'])envForm.elements[key].value=current[key]||'';repoRows.replaceChildren();for(const repo of current.repositories||[])addRepository(repo)}
envForm.elements.edit.onchange=fillEnvironment;envForm.elements.code.onchange=fillEnvironment;
envForm.onsubmit=safely(async e=>{const f=new FormData(e.target);const v={code:f.get('code'),groupCode:f.get('groupCode'),stage:f.get('stage'),cloud:f.get('cloud'),region:f.get('region'),accountId:f.get('accountId'),ackClusterId:f.get('ackClusterId'),repositories:[]};for(const row of repoRows.children){const field=name=>row.querySelector('[name="'+name+'"]').value.trim();v.repositories.push({purpose:field('purpose'),url:field('url'),baseBranch:field('baseBranch'),directory:field('directory')})}await api('environments'+(f.has('edit')?'/'+encodeURIComponent(v.code):''),f.has('edit')?'PATCH':'POST',v);await refreshEnvironments()});
refreshEnvironments().catch(()=>{});
</script>`
